### ISSUE TITLE
FR Have SM restart itself after update.

### ISSUE THREAD

**Issue by SpectralForce** [winglessraven/DeadMatterServerManager#18]
Have SM restart itself after update.

**Comment by winglessraven** [comment]
I've been looking into this and unfortunately it's looking like it'll be a bit of a nightmare to do this.  I can call the exe file when the install is committed but it runs the application with elevated status and the installer does not finish.  Not really ideal.

At some point in the future I may look at using a different installer solution that has the feature built in, but until then this one is on the back burner.

Thanks,
Dave.
