### ISSUE TITLE
 FR: Send email on crash

### ISSUE THREAD

**Issue by SpectralForce** [winglessraven/DeadMatterServerManager#19]
Have the SM send an email when it crashes/errors out.  People aren't always on discord and it would be good to know if the SM crashes as it kills the server too.

**Comment by winglessraven** [comment]
Hey Spectral,  just been thinking about this one.

I can add the option to send emails on server events (restart/crash etc) but not on application crash (if the application has crashed then the email function wouldn't be able to run).

Would it be any good to you to just have the email on server events?  If so I'll look to implement in the next update.

**Comment by SpectralForce** [comment]
That would be great. Emails to notify on crash & restarts.  Anyway to add in if theres an update for the server files?

**Comment by winglessraven** [comment]
Ok cool, I'll start working on it.

Server file update notifications is something I'm also looking into :)
