### ISSUE TITLE
Does not even open

### ISSUE THREAD

**Issue by Wamy-Dev** [winglessraven/DeadMatterServerManager#20]
Program does not open after install. It lets me click it and then nothing happens.

**Comment by winglessraven** [comment]
Can you go to %appdata% then DeadMatterServerManager and delete DMSM.cfg and try again?

**Comment by Wamy-Dev** [comment]
> Can you go to %appdata% then DeadMatterServerManager and delete DMSM.cfg and try again?

That worked! Thanks so much!
