### ISSUE TITLE
Failing to install - 2 step authentication

### ISSUE THREAD

**Issue by smooreace** [winglessraven/DeadMatterServerManager#4]
When doing an initial install the cmd window opens and starts the server install. the second the authentication code prompt shows up the window closes.

**Comment by winglessraven** [comment]
Only way I can replicate this is if I get my Steam login info incorrect.  I have MFA enabled and don't have any issue.

Can you go to your SteamCMD location /logs folder and send me the connection_log.txt?

**Comment by smooreace** [comment]
Sorry.. it was a PW issue. No way to auto handle that 2nd authentication is there?

**Comment by winglessraven** [comment]
No worries, there might be - I'll take a look into it!
