### ISSUE TITLE
Player names not appearing in player list

### ISSUE THREAD

**Issue by sunfireforge** [winglessraven/DeadMatterServerManager#6]
![image](https://user-images.githubusercontent.com/44955682/92987252-a54f2580-f475-11ea-93d6-b6142f5b9171.png)

**Comment by smooreace** [comment]
You might want to check existing open and closed issues before duplicating
them

**Comment by winglessraven** [comment]
Hopefully it'll work correctly in the next server patch.  Player names were working before the latest server version but the update broke it.

All code is in place to get player names once it's fixed.
